Repository C2FO/vfs, pull requests merged in 2021-09, with the labels that each got.

#94 Update reqs
  .github/workflows/go.yml
  .golangci.yml
  .gvmrc
  CHANGELOG.md
  backend/azure/options_test.go
  backend/gs/file_test.go
  backend/gs/location_test.go
  backend/os/file.go
  backend/sftp/options.go
  backend/testsuite/backend_integration_test.go
  go.mod
  go.sum
  mocks/S3API.go
  utils/authority.go
  utils/utils.go
  vfssimple/vfssimple.go
Labels: size/XXL

#95 Ep 7935 - S3 Multipart Download
  CHANGELOG.md
  backend/s3/file.go
  backend/s3/file_test.go
  backend/s3/options.go
  mocks/S3Downloader.go
Labels: size/L

#101 Rollback Seek validation on copy/move
  CHANGELOG.md
  backend/sftp/file.go
  backend/sftp/file_test.go
Labels: size/S
