Repository C2FO/vfs, pull requests merged in 2024-11, with the labels that each got.

#209 Fix typos
  CHANGELOG.md
  README.md
  backend/azure/client.go
  backend/azure/client_integration_test.go
  backend/azure/doc.go
  backend/azure/fileSystem_test.go
  backend/azure/file_test.go
  backend/azure/location_test.go
  backend/azure/mock_token.go
  backend/azure/token.go
  backend/backend_test.go
  backend/doc.go
  backend/ftp/dataconn.go
  backend/ftp/dataconn_test.go
  backend/ftp/doc.go
  backend/ftp/file.go
  backend/ftp/fileSystem.go
  backend/ftp/file_test.go
  backend/gs/bucketHandleWrapper.go
  backend/gs/doc.go
  backend/gs/fileSystem.go
  backend/gs/filesystem_test.go
  backend/mem/doc.go
  backend/mem/file.go
  backend/mem/fileSystem.go
  backend/mem/file_test.go
  backend/mem/location_test.go
  backend/os/doc.go
  backend/os/fileSystem.go
  backend/os/fileSystem_test.go
  backend/os/file_test.go
  backend/os/location.go
  backend/s3/doc.go
  backend/s3/fileSystem.go
  backend/s3/file_test.go
  backend/sftp/doc.go
  backend/sftp/file.go
  backend/sftp/fileSystem.go
  backend/sftp/fileSystem_test.go
  backend/sftp/location_test.go
  backend/sftp/options.go
  backend/sftp/options_test.go
  backend/testsuite/backend_integration_test.go
  backend/testsuite/doc.go
  doc.go
  docs/azure.md
  docs/backend.md
  docs/ftp.md
  docs/gs.md
  docs/mem.md
  docs/os.md
  docs/s3.md
  docs/sftp.md
  docs/utils.md
  mocks/StringFile.go
  utils/utils.go
  utils/utils_test.go
  vfs.go
  vfssimple/vfssimple_test.go
Labels: size/L

#210 Normalize whitespace
  .github/ISSUE_TEMPLATE/custom.md
  .golangci.yml
  CHANGELOG.md
  README.md
  backend/azure/doc.go
  backend/ftp/dataconn.go
  backend/ftp/dataconn_test.go
  backend/ftp/doc.go
  backend/ftp/file.go
  backend/ftp/fileSystem.go
  backend/ftp/file_test.go
  backend/ftp/location_test.go
  backend/gs/doc.go
  backend/gs/file.go
  backend/gs/location_test.go
  backend/mem/file.go
  backend/mem/fileSystem.go
  backend/mem/file_test.go
  backend/mem/location.go
  backend/mem/location_test.go
  backend/mem/readwriteseeker.go
  backend/os/file.go
  backend/os/file_test.go
  backend/s3/doc.go
  backend/s3/file.go
  backend/s3/fileSystem_test.go
  backend/s3/file_test.go
  backend/s3/options.go
  backend/sftp/doc.go
  backend/sftp/file.go
  backend/sftp/fileSystem.go
  backend/sftp/file_test.go
  backend/sftp/location.go
  backend/sftp/location_test.go
  backend/sftp/options.go
  backend/sftp/options_test.go
  backend/testsuite/backend_integration_test.go
  backend/testsuite/io_integration_test.go
  docs/azure.md
  docs/backend.md
  docs/delete_options.md
  docs/ftp.md
  docs/gs.md
  docs/mem.md
  docs/options.md
  docs/os.md
  docs/s3.md
  docs/sftp.md
  docs/utils.md
  docs/vfscp.md
  docs/vfssimple.md
  utils/utils.go
  utils/utils_test.go
  vfscp/vfscp.go
  vfssimple/vfssimple_test.go
Labels: size/L

#211 Configure mockery interfaces
  .mockery.yaml
  CHANGELOG.md
  backend/ftp/mocks/Client.go
  backend/ftp/mocks/DataConn.go
  backend/s3/mocks/DownloaderAPI.go
  backend/s3/mocks/S3API.go
  backend/s3/mocks/UploaderAPI.go
  backend/sftp/mocks/Client.go
  backend/sftp/mocks/FileInfo.go
  backend/sftp/mocks/ReadWriteSeekCloser.go
  mocks/File.go
  mocks/FileSystem.go
  mocks/Location.go
  mocks/Options.go
  mocks/Retry.go
Labels: size/XXL

#215 ensure readEOFSeen reset after reseting cursor with Seek
  CHANGELOG.md
  backend/s3/file.go
  backend/s3/file_test.go
Labels: size/M
