Repository C2FO/vfs, pull requests merged in 2024-01, with the labels that each got.

#151 Add support for hmac-sha1 and hmac-sha1-96
  CHANGELOG.md
  backend/sftp/options.go
Labels: size/XS

#153 Fixed #152 bug where s3 backend failed to read empty files
  CHANGELOG.md
  backend/s3/file.go
  backend/s3/file_test.go
Labels: size/M

#155 Sftp writes should truncate 154
  CHANGELOG.md
  backend/sftp/file.go
  backend/testsuite/backend_integration_test.go
  backend/testsuite/common.go
  backend/testsuite/io_integration_test.go
Labels: size/XL
