Repository C2FO/vfs, pull requests merged in 2024-02, with the labels that each got.

#159 Updated sftp backend to to fix issue where some servers return a gene…
  CHANGELOG.md
  backend/sftp/file.go
  backend/sftp/file_test.go
Labels: size/L

#157 Fixes #156 - Update os backend to use new io integration test suite
  CHANGELOG.md
  backend/mem/file_test.go
  backend/os/file.go
  backend/os/file_test.go
  backend/os/location_test.go
  utils/authority_test.go
  utils/utils_test.go
Labels: size/L

#161 Updated mem backend to comply with new io integration test suite at b…
  CHANGELOG.md
  backend/mem/file.go
  backend/mem/fileSystem.go
  backend/mem/file_test.go
  backend/mem/location.go
  backend/mem/readwriteseeker.go
Labels: size/XL

#164 Stream writes 146
  .mockery.yaml
  CHANGELOG.md
  backend/mem/file_test.go
  backend/s3/file.go
  backend/s3/fileSystem.go
  backend/s3/file_test.go
  backend/s3/location_test.go
  backend/s3/mocks/DownloaderAPI.go
  backend/s3/mocks/S3API.go
  backend/s3/mocks/UploaderAPI.go
  backend/s3/options.go
  docs/s3.md
  mocks/S3API.go
  mocks/S3Downloader.go
  vfssimple/vfssimple_test.go
Labels: size/XXL

#166 Update to go122 165
  .github/workflows/codecov.yml
  .github/workflows/go.yml
  .github/workflows/golangci-lint.yml
  .golangci.yml
  .gvmrc
  CHANGELOG.md
  backend/sftp/doc.go
  backend/sftp/options.go
  backend/sftp/options_test.go
  docs/sftp.md
  go.mod
  go.sum
Labels: size/L

#168 Added defer to file.Close()
  CHANGELOG.md
  README.md
  backend/azure/file.go
  backend/ftp/file.go
  backend/gs/file.go
  backend/mem/file.go
  backend/s3/file.go
  backend/sftp/file.go
Labels: size/L

#171 Fix bug where mem backend doesnt remove fs entries when location.Dele…
  CHANGELOG.md
  backend/mem/fileSystem.go
  backend/mem/location.go
Labels: size/S

#173 Update GS backend to comply with new io integration test suite. fixes…
  CHANGELOG.md
  backend/gs/file.go
  backend/gs/fileSystem.go
  backend/gs/filesystem_test.go
  backend/gs/objectHandleWrapper.go
  backend/gs/options_test.go
  backend/s3/file.go
  backend/s3/file_test.go
  backend/sftp/options.go
  utils/errors.go
  utils/utils.go
  utils/utils_test.go
Labels: size/XL
