Repository C2FO/vfs, pull requests merged in 2025-03, with the labels that each got.

#212 Switch to AWS SDK v2
  .mockery.yaml
  backend/s3/client.go
  backend/s3/doc.go
  backend/s3/file.go
  backend/s3/fileSystem.go
  backend/s3/fileSystem_test.go
  backend/s3/file_test.go
  backend/s3/location.go
  backend/s3/location_test.go
  backend/s3/mocks/Client.go
  backend/s3/mocks/S3API.go
  backend/s3/mocks/UploaderAPI.go
  backend/s3/options.go
  backend/s3/options_test.go
  docs/s3.md
  go.mod
  go.sum
  vfssimple/vfssimple_test.go
Labels: size/XXL

#232 Awsv2
  .github/workflows/codeql.yml
  .github/workflows/ensure_changelog.yml
  .github/workflows/go.yml
  CHANGELOG.md
  README.md
  backend/s3/file.go
  backend/testsuite/backend_integration_test.go
  backend/testsuite/common.go
  backend/testsuite/io_integration_test.go
  go.mod
  go.sum
Labels: size/L

#225 Azure az:// scheme
  CHANGELOG.md
  README.md
  backend/azure/client.go
  backend/azure/client_integration_test.go
  backend/azure/file.go
  backend/azure/fileSystem.go
  backend/azure/fileSystem_test.go
  backend/azure/file_test.go
  backend/azure/location.go
  backend/azure/location_test.go
  backend/azure/options.go
  backend/testsuite/backend_integration_test.go
  backend/testsuite/io_integration_test.go
  docs/azure.md
  vfssimple/vfssimple.go
  vfssimple/vfssimple_test.go
Labels: size/L

#239 Newfilesysytem options
  CHANGELOG.md
  README.md
  backend/azure/client_integration_test.go
  backend/azure/doc.go
  backend/azure/fileSystem.go
  backend/azure/fileSystem_test.go
  backend/azure/file_test.go
  backend/azure/location_test.go
  backend/azure/newFileSytemOption.go
  backend/azure/options.go
  backend/ftp/doc.go
  backend/ftp/fileSystem.go
  backend/ftp/fileSystem_test.go
  backend/ftp/file_test.go
  backend/ftp/newFileSystemOption.go
  backend/gs/bucketHandleWrapper.go
  backend/gs/doc.go
  backend/gs/file.go
  backend/gs/fileSystem.go
  backend/gs/file_test.go
  backend/gs/filesystem_test.go
  backend/gs/location.go
  backend/gs/location_test.go
  backend/gs/newFileSystemOption.go
  backend/gs/objectHandleWrapper.go
  backend/gs/options.go
  backend/mem/fileSystem.go
  backend/os/doc.go
  backend/os/fileSystem.go
  backend/os/fileSystem_test.go
  backend/s3/doc.go
  backend/s3/file.go
  backend/s3/fileSystem.go
  backend/s3/fileSystem_test.go
  backend/s3/file_test.go
  backend/s3/newFileSytemOption.go
  backend/sftp/doc.go
  backend/sftp/file.go
  backend/sftp/fileSystem.go
  backend/sftp/fileSystem_test.go
  backend/sftp/file_test.go
  backend/sftp/newFileSystemOption.go
  doc.go
  docs/backend.md
  docs/vfssimple.md
  go.mod
  go.sum
  logo.jpg
  options/options.go
  vfs.go
  vfssimple/vfssimple_test.go
Labels: size/XXL

#244 Fixes #243 - gs wrapped error issue
  CHANGELOG.md
  backend/gs/file.go
  backend/gs/file_test.go
  backend/gs/location.go
  backend/testsuite/backend_integration_test.go
  backend/testsuite/io_integration_test.go
  go.mod
  go.sum
Labels: size/M

#246 Add GetClient functions for each backend to allow for direct access t…
  CHANGELOG.md
  backend/azure/client.go
  backend/ftp/dataconn_test.go
  backend/ftp/fileSystem.go
  backend/ftp/file_test.go
  backend/ftp/options.go
  backend/gs/fileSystem.go
  backend/s3/fileSystem.go
  backend/s3/options.go
  backend/s3/options_test.go
  backend/sftp/fileSystem.go
  backend/sftp/options.go
  backend/sftp/options_test.go
  go.mod
  go.sum
Labels: size/L

#247 Added go-test-coverage action and remove codecove action since it has…
  .github/workflows/codecov.yml
  .github/workflows/codeql.yml
  .github/workflows/ensure_changelog.yml
  .github/workflows/go-test-coverage.yml
  .github/workflows/go.yml
  .github/workflows/golangci-lint.yml
  .testcoverage.yml
  CHANGELOG.md
  Makefile
  README.md
  backend/azure/client_test.go
  backend/azure/properties_test.go
  backend/azure/token_test.go
  backend/ftp/errors_test.go
  backend/gs/file.go
  backend/gs/newFileSystemOption_test.go
  backend/s3/options_test.go
  options/delete/allVersions_test.go
  options/newfile/contentType_test.go
Labels: size/XL
