Repository C2FO/vfs, pull requests merged in 2025-09, with the labels that each got.

#276 Fix typos and minor grammar issues
  CHANGELOG.md
  LICENSE.md
  README.md
  backend/azure/client_integration_test.go
  backend/azure/file.go
  backend/azure/fileSystem_test.go
  backend/azure/file_test.go
  backend/azure/newFileSystemOption.go
  backend/azure/options_test.go
  backend/ftp/doc.go
  backend/ftp/file.go
  backend/ftp/file_test.go
  backend/ftp/location.go
  backend/ftp/location_test.go
  backend/gs/file.go
  backend/gs/fileSystem.go
  backend/mem/file_test.go
  backend/s3/file.go
  backend/s3/newFileSystemOption.go
  backend/testsuite/io_integration_test.go
  contrib/vfsevents/CHANGELOG.md
  contrib/vfsevents/README.md
  contrib/vfsevents/watchers/gcsevents/gcsevents.go
  doc.go
  docs/azure.md
  docs/ftp.md
Labels: size/M

#277 Minor whitespace cleanup
  .github/ISSUE_TEMPLATE/custom.md
  .github/workflows/ensure_changelog.yml
  .github/workflows/go-test-coverage.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/scripts/changelog.sh
  .github/workflows/scripts/module-ci.sh
  .testcoverage.yml
  CHANGELOG.md
  README.md
  backend/ftp/doc.go
  backend/ftp/location.go
  backend/gs/fileSystem.go
  backend/mem/location.go
  backend/s3/options.go
  backend/sftp/doc.go
  backend/sftp/file.go
  backend/sftp/location.go
  backend/testsuite/backend_integration_test.go
  contrib/lockfile/CHANGELOG.md
  contrib/lockfile/README.md
  contrib/vfsevents/CHANGELOG.md
  contrib/vfsevents/README.md
  contrib/vfsevents/watchers/fsnotify/README.md
  contrib/vfsevents/watchers/fsnotify/fsnotify.go
  contrib/vfsevents/watchers/gcsevents/README.md
  contrib/vfsevents/watchers/s3events/README.md
  contrib/vfsevents/watchers/vfspoller/README.md
  docs/ftp.md
  docs/options.md
  docs/s3.md
  docs/sftp.md
  utils/authority/authority.go
Labels: size/L

#280 More consistent unit test assertions
  CHANGELOG.md
  backend/azure/client_integration_test.go
  backend/azure/token_test.go
  backend/backend_test.go
  backend/ftp/dataconn_test.go
  backend/ftp/errors_test.go
  backend/ftp/file_test.go
  backend/ftp/location_test.go
  backend/gs/newFileSystemOption_test.go
  backend/mem/file_test.go
  backend/mem/location_test.go
  backend/os/fileSystem_test.go
  backend/os/file_test.go
  backend/s3/file_test.go
  backend/sftp/concurrency_test.go
  backend/sftp/fileSystem_test.go
  backend/sftp/file_test.go
  backend/sftp/location_test.go
  backend/testsuite/backend_integration_test.go
  contrib/lockfile/CHANGELOG.md
  contrib/lockfile/lockfile_test.go
  contrib/vfsevents/CHANGELOG.md
  contrib/vfsevents/vfsevents_test.go
  contrib/vfsevents/watchers/fsnotify/debounce_test.go
  contrib/vfsevents/watchers/fsnotify/fsnotify_test.go
  contrib/vfsevents/watchers/gcsevents/gcsevents_test.go
  contrib/vfsevents/watchers/s3events/s3events_test.go
  contrib/vfsevents/watchers/vfspoller/vfspoller_test.go
  utils/errors_test.go
  vfssimple/vfssimple_test.go
Labels: size/L

#281 Use mockery for Azure unit tests
  .mockery.yaml
  CHANGELOG.md
  backend/azure/client.go
  backend/azure/fileSystem_test.go
  backend/azure/file_test.go
  backend/azure/location_test.go
  backend/azure/mock_client.go
  backend/azure/mocks/Client.go
  backend/azure/properties.go
  backend/azure/types/properties.go
  backend/azure/types/types.go
  docs/azure.md
Labels: size/XL

#284 Lint vfsintegration test code
  .github/workflows/golangci-lint.yml
  .prenup.yml
  CHANGELOG.md
  Makefile
  backend/azure/client.go
  backend/azure/types/types.go
  backend/testsuite/backend_integration_test.go
Labels: size/M

#285 Use utils.Ptr where possible
  CHANGELOG.md
  backend/azure/client_test.go
  backend/azure/properties_test.go
  backend/ftp/file.go
  backend/ftp/options_test.go
  backend/mem/file.go
  backend/os/file.go
  backend/s3/file_test.go
  backend/sftp/file.go
  backend/sftp/options.go
  contrib/vfsevents/CHANGELOG.md
  contrib/vfsevents/watchers/vfspoller/vfspoller_test.go
  options/newfile/contentType.go
Labels: size/M

#288 Fix typed nil pointer bug in sftp backend. Fixes #287.
  CHANGELOG.md
  backend/sftp/fileSystem.go
Labels: size/XS
