Repository C2FO/vfs, pull requests merged in 2025-01, with the labels that each got.

#207 Windows support
  .github/workflows/go.yml
  CHANGELOG.md
  backend/azure/fileSystem.go
  backend/mem/file_test.go
  backend/os/file.go
  backend/os/fileSystem.go
  backend/os/file_test.go
  backend/os/location.go
  backend/os/location_test.go
  backend/sftp/options.go
  backend/sftp/options_test.go
  utils/utils.go
  utils/utils_test.go
Labels: size/L

#221 Resolve x net security vulnerability
  go.mod
  go.sum
Labels: size/S

#213 Switch to new Azure SDK
  CHANGELOG.md
  backend/azure/client.go
  backend/azure/client_integration_test.go
  backend/azure/doc.go
  backend/azure/file.go
  backend/azure/file_test.go
  backend/azure/mock_client.go
  backend/azure/mock_token.go
  backend/azure/options.go
  backend/azure/options_test.go
  backend/azure/properties.go
  backend/azure/token.go
  docs/azure.md
  go.mod
  go.sum
Labels: size/XL

#222 update dependencies, add 6.35.0 release
  CHANGELOG.md
  go.mod
  go.sum
Labels: size/L

#223 azure: Upload Content-Type option
  CHANGELOG.md
  backend/azure/client.go
Labels: size/S

#219 add support for assumed role credentials in the s3 backend
  CHANGELOG.md
  backend/s3/options.go
  backend/s3/options_test.go
  docs/s3.md
Labels: size/M
